name: .NET Core pull_request on develop branch

on:
  pull_request:
    branches: [develop]

env:
  PROJECT_NAME: MarketplaceService
  DOCKER_ORGANIZATION: s652
  DOCKER_REPOSITORY: marketplace-service

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Decrypt the gpg encrypted config files
      - name: Decrypt the gpg encrypted config files
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.GPG_PASSPHRASE }} --output ./${{ env.PROJECT_NAME }}/appsettings.json --decrypt ./${{ env.PROJECT_NAME }}/appsettings.json.gpg

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build
        run: dotnet build
      
      # Test the project
      - name: Test
        run: dotnet test
      
      # Runs SonarCloud scan    
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_ACCESS_TOKEN }}